TRAIN:
  ENABLE: False # default True
  DATASET: h2of ## the flow dataset; 
  # DATASET: h2o
  BATCH_SIZE: 16
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: False
X3D:
  WIDTH_FACTOR: 2.0
  DEPTH_FACTOR: 2.2
  BOTTLENECK_FACTOR: 2.25
  DIM_C5: 2048
  DIM_C1: 12
TEST:
  ENABLE: True
  DATASET: h2of
  BATCH_SIZE: 32
  NUM_SPATIAL_CROPS: 3
  CHECKPOINT_FILE_PATH: ""
  NUM_ENSEMBLE_VIEWS: 9
  CONTEXT_APPEND: 0.

H2O:
  BACKGROUND_CLASS: True
  NOUN_VERB: False
  NOUN_VERB_WEIGHT: [1, 1, 1]
  FRAME_FOLDER: "flow/rgb256" # Flow Folder? 
  # FRAME_FOLDER: "rgb256"
  FLOW_ENABLE: True
  FRAME_TEMPL: "flow_{}_{:05d}.jpg"

AUG: # 看看里面有没有其他的参数; 
  ENABLE: False

DATA:

  #NUM_FRAMES: 32 # 对应的窗口的尺寸是32 * 2
  #SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  #TRAIN_JITTER_SCALES: [512, 640]
  #TRAIN_CROP_SIZE: 448 
  TEST_CROP_SIZE: 256
  NUM_FRAMES: 13
  SAMPLING_RATE: 6
  INPUT_CHANNEL_NUM: [2]
  # INPUT_CHANNEL_NUM: [3]
  DECODING_BACKEND: torchvision
  COLOR_RND_GRAYSCALE: 0.
  TIME_DIFF_PROB: 0.
  CONTEXT_APPEND: 0.1
  SSL_COLOR_JITTER: False
  # TRAIN_JITTER_FPS: 3.0
  STD: [0.5, 0.5]
  MEAN: [0.226, 0.226]
RESNET:
  ZERO_INIT_FINAL_BN: True
  TRANS_FUNC: x3d_transform
  STRIDE_1X1: False
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
  WEIGHT_DECAY: 0.0
SOLVER:
  BASE_LR: 0.001 # 16 machine # base 0.1
  BASE_LR_SCALE_NUM_SHARDS: True
  LR_POLICY: cosine
  MAX_EPOCH: 1000
  WEIGHT_DECAY: 5e-5
  WARMUP_EPOCHS: 35.0
  WARMUP_START_LR: 0.0001 # base: 0.01
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 37
  ARCH: resnet
  MODEL_NAME: flow_resnet152
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
DATA_LOADER:
  NUM_WORKERS: 20
  PIN_MEMORY: True
NUM_GPUS: 1
RNG_SEED: 0 
OUTPUT_DIR: ""