TRAIN:
  ENABLE: False
  DATASET: h2o
  BATCH_SIZE: 16
  EVAL_PERIOD: 50
  CHECKPOINT_PERIOD: 50
  AUTO_RESUME: False
  # CHECKPOINT_TYPE: "caffe2"
DATA:
  NUM_FRAMES: 32 # 对应的窗口的尺寸是32 * 2
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  #TRAIN_JITTER_SCALES: [512, 640]
  #TRAIN_CROP_SIZE: 448 
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3, 3]
  CONTEXT_APPEND: 0.1
  # STD: [0.2892, 0.2893, 0.2895]
  # MEAN: [0.4183, 0.4178, 0.4176]
H2O:
  BACKGROUND_CLASS: True
  NOUN_VERB: False
  NOUN_VERB_WEIGHT: [1, 1, 1]
  # FRAME_FOLDER: "rgb256"
  FRAME_FOLDER: "rgb448"
  # FLOW_ENABLE: True
  FRAME_TEMPL: "{:06d}.jpg"
SLOWFAST:
  ALPHA: 8
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 5
RESNET:
  ZERO_INIT_FINAL_BN: True
  # WIDTH_PER_GROUP: 64
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50 # dict_keys([18, 50, 101])
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [2, 2]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [1, 1]]

NONLOCAL:
  LOCATION: [[[], []], [[], []], [[], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
SOLVER:
  # BASE_LR: 0.2
  BASE_LR: 0.1
  LR_POLICY: cosine
  MAX_EPOCH: 1000
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  # WARMUP_EPOCHS: 34.0
  WARMUP_EPOCHS: 34.0
  # WARMUP_START_LR: 0.03
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd

MODEL:
  NUM_CLASSES: 37
  ARCH: slowfast
  MODEL_NAME: SlowFast
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5

TEST:
  ENABLE: True
  DATASET: h2o
  BATCH_SIZE: 32
  CHECKPOINT_FILE_PATH: ""
  CONTEXT_APPEND: 0.
DATA_LOADER:
  NUM_WORKERS: 16
  PIN_MEMORY: True
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: ""