TRAIN:
  ENABLE: False # default True
  DATASET: h2o
  BATCH_SIZE: 16
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: False
X3D:
  WIDTH_FACTOR: 2.0
  DEPTH_FACTOR: 2.2
  BOTTLENECK_FACTOR: 2.25
  DIM_C5: 2048
  DIM_C1: 12
TEST:
  ENABLE: True
  DATASET: h2o
  BATCH_SIZE: 32
  NUM_SPATIAL_CROPS: 3
  CHECKPOINT_FILE_PATH: ""
  NUM_ENSEMBLE_VIEWS: 9
  CONTEXT_APPEND: 0.
H2O:
  BACKGROUND_CLASS: True
  # BACKGROUND_CLASS: False
  NOUN_VERB: False
  NOUN_VERB_WEIGHT: [1, 1, 1]
  FRAME_FOLDER: "rgb448"

DATA:
  NUM_FRAMES: 13
  SAMPLING_RATE: 6
  TRAIN_JITTER_SCALES: [182, 228]
  TRAIN_CROP_SIZE: 160
  # TEST_CROP_SIZE: 160 # use if TEST.NUM_SPATIAL_CROPS: 1
  TEST_CROP_SIZE: 182 # use if TEST.NUM_SPATIAL_CROPS: 3
  INPUT_CHANNEL_NUM: [3]
  DECODING_BACKEND: torchvision
  COLOR_RND_GRAYSCALE: 0.
  TIME_DIFF_PROB: 0.
  CONTEXT_APPEND: 0.1
RESNET:
  ZERO_INIT_FINAL_BN: True
  TRANS_FUNC: x3d_transform
  STRIDE_1X1: False
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
  WEIGHT_DECAY: 0.0
SOLVER:
  BASE_LR: 0.1 # 16 machine
  BASE_LR_SCALE_NUM_SHARDS: True
  LR_POLICY: cosine
  MAX_EPOCH: 300
  WEIGHT_DECAY: 5e-5
  WARMUP_EPOCHS: 35.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 37
  ARCH: x3d
  MODEL_NAME: X3D
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
DATA_LOADER:
  NUM_WORKERS: 20
  PIN_MEMORY: True
NUM_GPUS: 1
RNG_SEED: 0 
OUTPUT_DIR: ""
